DROP DATABASE IF EXISTS exam;
CREATE DATABASE exam;

USE exam;

DROP TABLE IF EXISTS countries;
CREATE TABLE countries (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name varchar(50) NOT NULL
);

DROP TABLE IF EXISTS cities ;
CREATE TABLE cities (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name varchar(50) NOT NULL,
	country_id int UNSIGNED,
	FOREIGN KEY (country_id) REFERENCES  countries(id) ON DELETE RESTRICT
);

DROP TABLE IF EXISTS clients;
CREATE TABLE clients (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name varchar(50) NOT NULL,
	birthday datetime DEFAULT NULL,
	city_id int UNSIGNED DEFAULT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (city_id) REFERENCES  cities(id) ON DELETE RESTRICT
	
);

DROP TABLE IF EXISTS autos;
CREATE TABLE autos (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	vendor varchar(50) NOT NULL,
	model varchar(50) NOT NULL,
);

DROP TABLE IF EXISTS client_auto;
CREATE TABLE client_auto (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	client_id int UNSIGNED NOT NULL,
	model_id int UNSIGNED NOT NULL,
	odometer int NOT NULL,
	engine_type_id int UNSIGNED NOT NULL,
	engine_volume float(3,1) NOT NULL,
	car_vin varchar(17) NOT NULL,
	FOREIGN KEY () REFERENCES  () ON DELETE CASCADE
);
